// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://zgfeaagixqddwgqpycwu.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InpnZmVhYWdpeHFkZHdncXB5Y3d1Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQxOTk0NjEsImV4cCI6MjA1OTc3NTQ2MX0.xU8tBHW7WWYDgsmxT-_gvnrnBKnSDWCH90RroHIaCMU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);